PhoenixGL: phoenix::PhRenderSystem Class Reference
phoenix::PhRenderSystem Class Reference
The render system.
#include <svn/0.3/libPhoenixGL/PhRenderSystem.h>
Classes
struct PhGlyph
Public Member Functions
PhRenderSystem ()
Construct.
~PhRenderSystem ()
Destruct.
void setWindowCaption (const std::string &str)
Set window caption.
const bool run ()
Run.
const float getFPS () const
Get frames per second.
const double getTicks () const
Get ticks.
const bool initSystem (const PhVector2d &sc=PhVector2d(640, 480), const bool &fs=false)
Init system.
const PhVector2d & getScreenSize () const
Get screen size.
PhTexture * loadTexture (const std::string &filename, const bool &linear=true)
Load texture.
void drawIndexedTriangleList (GLfloat *vertices, GLfloat *normals, GLfloat *tcoords, GLuint *colors, GLuint *indexlist, const int &tricount)
Draw indexed trangle list.
void drawIndexedTriangleFan (GLfloat *vertices, GLfloat *normals, GLfloat *tcoords, GLuint *colors, GLuint *indexlist, const int &vertcount)
Draw indexed trangle fan.
void drawIndexedLine (GLfloat *vertices, GLfloat *normals, GLfloat *tcoords, GLuint *colors, GLuint *indexlist, const int &vertcount)
Draw indexed line.
void drawLine (const PhVector2d &v1=PhVector2d(0, 0), const PhVector2d &v2=PhVector2d(0, 0), const float &depth=0.0f, const PhColor &a=PhColor(255, 255, 255), const PhColor &b=PhColor(255, 255, 255, 255))
Draw line.
void drawRay (const PhVector2d &origin=PhVector2d(0, 0), const PhVector2d &ray=PhVector2d(0, 0), const float &depth=0.0f, const PhColor &a=PhColor(255, 255, 255), const PhColor &b=PhColor(255, 255, 255, 255))
Draw ray.
void drawRectangle (const PhRect &r=PhRect(0, 0, 0, 0), const float &depth=0.0f, const PhColor &a=PhColor(255, 255, 255), const PhColor &b=PhColor(255, 255, 255), const PhColor &c=PhColor(255, 255, 255), const PhColor &d=PhColor(255, 255, 255))
Draw rectangle.
void drawPolygon (const PhPolygon &P, const float &depth=0.0f, const PhColor &a=PhColor(255, 255, 255))
Draws a polygon.
void drawTexturedPolygon (const PhPolygon &P, PhTexture *texture, const float &depth=0.0f, const PhColor &a=PhColor(255, 255, 255), const bool &eyespace=false)
Draws a textured polygon.
void drawTexture (PhTexture *source, const PhVector2d &pos, const float &depth=0.0f, const float &rot=0.0f, const PhVector2d &scale=PhVector2d(1.0f, 1.0f), const PhColor &color=PhColor(255, 255, 255), const bool &hflip=false, const bool &vflip=false)
Draw texture.
void drawTexturePart (PhTexture *source, const PhVector2d &pos, const PhRect &rect, const float &depth=0.0f, const float &rot=0.0f, const PhVector2d &scale=PhVector2d(1.0f, 1.0f), const PhColor &color=PhColor(255, 255, 255), const bool &hflip=false, const bool &vflip=false)
Draw texture part.
void drawText (const std::string &text, const PhVector2d &pos, const PhColor &color=PhColor(255, 255, 255), const float &depth=0.0f)
Draw text.
void setFont (PhTexture *t)
Set font.
PhTexture * getFont () const
Get font.
PhEventHandler * getEventHandler () const
Get event handler.
PhTextureManager * getTextureManager () const
Get texture manager.
PhLogManager * getLogManager () const
Get log manager.
PhVertexLightSystem * getVertexLightSystem () const
Get vertex light system.
void setVertexLightSystem (PhVertexLightSystem *v)
Set vertex light system.
void setBlendMode (const GLenum &src, const GLenum &dst)
Set blend mode.
void setDefaultBlendMode ()
Set defualt blend mode.
void setVertexLighting (const bool &a)
Set vertex light state.
const bool & getVertexLighting () const
Get vertex light state.
Detailed Description
The render system.
This is the heart of phoenix. On the basic level it provides a layer over OpenGL. It provides primitive drawing functions as well as functions for drawing textures and text. It provides functions for loading textures, as well as manipulating the window.
Member Function Documentation
void phoenix::PhRenderSystem::drawIndexedLine (GLfloat * vertices, GLfloat * normals, GLfloat * tcoords, GLuint * colors, GLuint * indexlist, const int & vertcount)
Draw indexed line.
Provides the ability to quickly draw an indexed line to OpenGL.
Parameters:
vertices The list of vertices in the triangle list.
normals The list of normals for each vertex (this is usually just <0,0,1>).
tcoords The list of texture coords for each vertex.
colors The list of colors for each vertex.
indexlist The order of the vertices.
vertcount The number of vertices.
See also:
drawIndexedTriangleFran(), drawIndexedTriangleList(), drawLine(), drawRay()
void phoenix::PhRenderSystem::drawIndexedTriangleFan (GLfloat * vertices, GLfloat * normals, GLfloat * tcoords, GLuint * colors, GLuint * indexlist, const int & vertcount)
Draw indexed trangle fan.
Provides the ability to quickly draw an indexed triangle fan to OpenGL.
Parameters:
vertices The list of vertices in the triangle fan.
normals The list of normals for each vertex (this is usually just <0,0,1>).
tcoords The list of texture coords for each vertex.
colors The list of colors for each vertex.
indexlist The order of the vertices.
vertcount The number of vertices.
See also:
drawIndexedTriangleList(), drawIndexedLine()
void phoenix::PhRenderSystem::drawIndexedTriangleList (GLfloat * vertices, GLfloat * normals, GLfloat * tcoords, GLuint * colors, GLuint * indexlist, const int & tricount)
Draw indexed trangle list.
Provides the ability to quickly draw an indexed triangle list to OpenGL.
Parameters:
vertices The list of vertices in the triangle list.
normals The list of normals for each vertex (this is usually just <0,0,1>).
tcoords The list of texture coords for each vertex.
colors The list of colors for each vertex.
indexlist The list of each vertex that makes up each triangle.
tricount The number of trangles.
See also:
drawIndexedTriangleFan(), drawIndexedLine()
void phoenix::PhRenderSystem::drawLine (const PhVector2d & v1 = PhVector2d(0, 0), const PhVector2d & v2 = PhVector2d(0, 0), const float & depth = 0.0f, const PhColor & a = PhColor(255, 255, 255), const PhColor & b = PhColor(255, 255, 255, 255))
Draw line.
Draws a 2D line with a color for each vertex.
Parameters:
v1 The vector to the first point of the line.
v2 The vector to the second point of the line.
depth The depth of the line.
a Color of the first vertex.
b Color of the second vertex.
See also:
drawRay()
void phoenix::PhRenderSystem::drawPolygon (const PhPolygon & P, const float & depth = 0.0f, const PhColor & a = PhColor(255, 255, 255))
Draws a polygon.
Simply draws a polygon with the given depth and color.
Parameters:
P Polygon to draw.
depth Depth to draw it at.
a Color to draw it with.
textured If this is false, then texturing will be disabled while this polygon is draw. If it is enabled then the currently binded texture will be used.
void phoenix::PhRenderSystem::drawRay (const PhVector2d & origin = PhVector2d(0, 0), const PhVector2d & ray = PhVector2d(0, 0), const float & depth = 0.0f, const PhColor & a = PhColor(255, 255, 255), const PhColor & b = PhColor(255, 255, 255, 255))
Draw ray.
Draws a 2D ray with a color for each vertex starting from the origin.
Parameters:
origin The vector to the origin.
ray The vector trepresentation of the ray.
depth The depth of the ray.
a Color of the first vertex.
b Color of the second vertex.
See also:
drawLine()
void phoenix::PhRenderSystem::drawRectangle (const PhRect & r = PhRect(0, 0, 0, 0), const float & depth = 0.0f, const PhColor & a = PhColor(255, 255, 255), const PhColor & b = PhColor(255, 255, 255), const PhColor & c = PhColor(255, 255, 255), const PhColor & d = PhColor(255, 255, 255))
Draw rectangle.
Draws a rectangle with a color for each corner.
Parameters:
r The rectangle to be drawn.
depth The depth of the rectangle.
a Color of the top-left corner.
b Color of the top-right corner.
c Color of the bottom-right corner.
d Color of the bottom-left corner.
void phoenix::PhRenderSystem::drawText (const std::string & text, const PhVector2d & pos, const PhColor & color = PhColor(255, 255, 255), const float & depth = 0.0f)
Draw text.
Draws a texture using the current font.
Parameters:
text The text to draw.
pos Where to draw it at.
color The color of the font.
depth The depth to draw it at.
See also:
loadFont()
void phoenix::PhRenderSystem::drawTexture (PhTexture * source, const PhVector2d & pos, const float & depth = 0.0f, const float & rot = 0.0f, const PhVector2d & scale = PhVector2d(1.0f, 1.0f), const PhColor & color = PhColor(255, 255, 255), const bool & hflip = false, const bool & vflip = false)
Draw texture.
Parameters:
source The texture to draw.
pos Where to draw it at.
depth The depth to draw it at.
rot Rotation (in degrees).
scale Scale.
color Color.
hflip If true, flip horizontally.
vflip If true, vertically.
See also:
drawTexturePart()
void phoenix::PhRenderSystem::drawTexturedPolygon (const PhPolygon & P, PhTexture * texture, const float & depth = 0.0f, const PhColor & a = PhColor(255, 255, 255), const bool & eyespace = false)
Draws a textured polygon.
Draws a polygon with the given depth and color and applies the given texture to the polygon.
Parameters:
P Polygon to draw.
texture The texture that will be applied to the polygon.
depth Depth to draw it at.
a Color to draw it with.
eyespace If true, it generates texture coordinates in eyespace instead of object space.
void phoenix::PhRenderSystem::drawTexturePart (PhTexture * source, const PhVector2d & pos, const PhRect & rect, const float & depth = 0.0f, const float & rot = 0.0f, const PhVector2d & scale = PhVector2d(1.0f, 1.0f), const PhColor & color = PhColor(255, 255, 255), const bool & hflip = false, const bool & vflip = false)
Draw texture part.
Draws a texture with a clipping rectangle.
Parameters:
source The texture to draw.
pos Where to draw it at.
rect The clipping rectangle.
depth The depth to draw it at.
rot Rotation (in degrees).
scale Scale.
color Color.
hflip If true, flip horizontally.
vflip If true, vertically.
See also:
drawTexture()
PhEventHandler* phoenix::PhRenderSystem::getEventHandler () const [inline]
Get event handler.
Returns:
A pointer to the event handler used by the system.
PhTexture* phoenix::PhRenderSystem::getFont () const [inline]
Get font.
Returns:
The current textured used as a font.
See also:
setFont()
const float phoenix::PhRenderSystem::getFPS () const [inline]
Get frames per second.
Returns:
The average FPS over the total run time of the program.
References phoenix::PhTimer::getTicks().
PhLogManager* phoenix::PhRenderSystem::getLogManager () const [inline]
Get log manager.
Returns:
A pointer to the log manager.
const PhVector2d& phoenix::PhRenderSystem::getScreenSize () const [inline]
Get screen size.
Returns:
The size of the screen.
PhTextureManager* phoenix::PhRenderSystem::getTextureManager () const [inline]
Get texture manager.
Returns:
A pointer to the texture manager.
const double phoenix::PhRenderSystem::getTicks () const [inline]
Get ticks.
Returns:
The number of ticks (ms) that have occured since the engine started.
References phoenix::PhTimer::getTicks().
const bool& phoenix::PhRenderSystem::getVertexLighting () const [inline]
Get vertex light state.
Gets the current state of vertex lighting.
PhVertexLightSystem* phoenix::PhRenderSystem::getVertexLightSystem () const [inline]
Get vertex light system.
Returns:
A pointer to vertex light system.
const bool phoenix::PhRenderSystem::initSystem (const PhVector2d & sc = PhVector2d(640, 480), const bool & fs = false)
Init system.
Sets up everything needed by the render system. This should be called at the beginning of the program and is required to use any of the render system's functions.
Parameters:
sc The size of the screen (default 640,480).
fs Full screen (default false).
Returns:
True if it succeeded in creating a window & an opengl render context.
PhTexture* phoenix::PhRenderSystem::loadTexture (const std::string & filename, const bool & linear = true)
Load texture.
Loads an image as a texture and adds it to the texture manager for garbage collection. Currently only .png files are supported. More formats are planned.
Parameters:
filename The filename of the image to load.
linear Tells the loader to use linear filtering or not. (default true).
Note:
Use nearest filtering for tilemaps, or anything that may look bad when scaled.
Textures must be sizes that are a power of two. NPOT textures will experience artifacts.
const bool phoenix::PhRenderSystem::run ()
Run.
This is one of the required functions of the render system. This should be called before all drawing functions and should be called once per frame. (perferably in a while loop).
void phoenix::PhRenderSystem::setBlendMode (const GLenum & src, const GLenum & dst) [inline]
Set blend mode.
Sets the blend mode for opengl. The defualt blend mode is GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA.
Parameters:
src The source factor, can be GL_ZERO, GL_ONE, GL_DST_COLOR, GL_ONE_MINUS_DST_COLOR, GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA, GL_DST_ALPHA, GL_ONE_MINUS_DST_ALPHA, and GL_SRC_ALPHA_SATURATE
dst The destination factor, can be GL_ZERO, GL_ONE, GL_SRC_COLOR, GL_ONE_MINUS_SRC_COLOR, GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA, GL_DST_ALPHA, and GL_ONE_MINUS_DST_ALPHA
See also:
setDefaultBlendMode()
Referenced by setDefaultBlendMode().
void phoenix::PhRenderSystem::setDefaultBlendMode () [inline]
Set defualt blend mode.
Restores the engine to it's default blend mode (GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA).
See also:
setBlendMode()
References setBlendMode().
void phoenix::PhRenderSystem::setFont (PhTexture * t) [inline]
Set font.
Sets the font to the given texture.
Parameters:
t The new font.
See also:
getFont()
void phoenix::PhRenderSystem::setVertexLighting (const bool & a) [inline]
Set vertex light state.
Enables or disables vertex lighting.
void phoenix::PhRenderSystem::setVertexLightSystem (PhVertexLightSystem * v) [inline]
Set vertex light system.
Allows you to change the light system to another
void phoenix::PhRenderSystem::setWindowCaption (const std::string & str) [inline]
Set window caption.
Parameters:
str The new caption of the window.
The documentation for this class was generated from the following file:
svn/0.3/libPhoenixGL/PhRenderSystem.h